### ISSUE TITLE
fatal bug in universal fix dropbox links

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#13]
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:163
                if ($(link).attr('href').indexOf('drop_box') != -1) {
                                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at Node.$.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:163:41)
    at initialize.exports.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\cheerio\lib\api\traversing.js:300:24)
    at parseItem (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:162:22)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:37:13)
    at asyncLib.waterfall (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:66:13)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:473:16
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5315:29)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at constructCanvasAssignments (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:111:17)
    at canvas.get (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-fix-dropbox-links.js:138:13)
```

Error occurred in pathway course 22480 (GS 120)

**Comment by csammcgrath** [comment]
@danverde, can you please try this again? It should work!

**Comment by danverde** [comment]
Nope, It's still broken

**Comment by zlw11063** [comment]
I've fixed this issue. It just needed a truthy check alongside the includes.
