### ISSUE TITLE
fatal bug in universal description quicklinks

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#14]
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:90
                if ($(link).attr('href').indexOf(check) != -1) {
                                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at Node.$.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:90:41)
    at initialize.exports.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\cheerio\lib\api\traversing.js:300:24)
    at checkPages (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:89:22)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:35:13)
    at buildCanvasArray (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:64:17)
    at canvas.get (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:306:13)
    at paginate (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:40:13)
    at Object.callReturned [as callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:216:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2257:31
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
```

Error occurred in pathway course 22480 (GS 120)

**Comment by csammcgrath** [comment]
@danverde, can you please try running this again and see if this now works?

**Comment by danverde** [comment]
I ran it on the same course and this is what I got:
```
throw new Error('Hmm, there is a problem with the course. An assignment never existed in Brightspace but is trying to exist in Canvas somehow.');
                            ^

Error: Hmm, there is a problem with the course. An assignment never existed in Brightspace but is trying to exist in Canvas somehow.
    at Node.$.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:110:35)
    at initialize.exports.each (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\cheerio\lib\api\traversing.js:300:24)
    at checkPages (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:101:26)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:35:13)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:67:13)
    at beginProcess (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:29:9)
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:18:9)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
```

**Comment by csammcgrath** [comment]
This should be fixed with the latest update in the branch.

**Comment by zlw11063** [comment]
Looks like it isn't an issue anymore.
