### ISSUE TITLE
another fatal bug in universal-description-quicklinks

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#47]
It happened in CIT 240 (D2L OU: 61928)

```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:179
            return page.html_url;
                        ^

TypeError: Cannot read property 'html_url' of undefined
    at getCanvasUrl (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:179:25)
    at pageProperties.forEach (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:200:26)
    at Array.forEach (<anonymous>)
    at getCorrectLinks (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:199:24)
    at checkPages (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:123:17)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:39:13)
    at checkArrays (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:71:13)
    at beginProcess (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:33:9)
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-description-quicklinks.js:22:9)
```

**Comment by sethchilders92** [comment]
Just merged with Sam's branch that hopefully fixed this. Let me know if it is still broken. @danverde

**Comment by zlw11063** [comment]
Seems fixed.
