### ISSUE TITLE
action-series-master: canvasAssignments.Clone is not a function

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#5]
Full error:
```
TypeError: canvasAssignments.clone is not a function
    at canvas.get (C:\Users\Danverde\Documents\CONVERSION\action-series-master\actions\universal-fix-dropbox-links.js:158:31)
    at paginate (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\canvas.js:43:13)
    at Object.callReturned [as callback] (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\canvas.js:220:9)
    at C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\node_modules\async\dist\async.js:2257:31
    at C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\node_modules\async\dist\async.js:958:16
    at updateRateLimit (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\canvas.js:115:17)
    at updateRateLimit (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\canvas.js:61:13)
    at Request.request [as _callback] (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\canvas.js:103:13)
    at Request.self.callback (C:\Users\Danverde\Documents\CONVERSION\canvas-wrapper\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
```

**Comment by csammcgrath** [comment]
Fixed.
