### ISSUE TITLE
fatal bug in universal-broken-quicklinks

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#50]
It broke in CIT 325 (106278)
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-broken-quicklinks.js:32
                if ($(link).attr('href').includes('quickLink')) {
                                        ^

TypeError: Cannot read property 'includes' of undefined
    at links.forEach.link (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-broken-quicklinks.js:32:41)
    at Array.forEach (<anonymous>)
    at action (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-broken-quicklinks.js:30:19)
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-broken-quicklinks.js:48:5)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-naming-conventions.js:199:9)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
```

**Comment by sethchilders92** [comment]
This grandchild is no longer used. It was originally created for Brother Moore's team, but we then created a different grandchild module that went in and instead of logging the broken quicklinks, it fixes them.
