### ISSUE TITLE
Error in Description Quicklinks

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#54]
```
C:\Users\Xache… error                     message: You may want to look into this course. Assignment (Published) appears to be missing from the course. stack: Error: You may want to look into this course. Assignment (Published) appears to be missing from the course.
    at Course.error (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\logger\Logger.js:82:19)
    at pageProperties.forEach (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:189:28)
    at Array.forEach (<anonymous>)
    at getCorrectLinks (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:185:28)
    at checkPages (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:138:21)
    at checkArrays (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:55:17)
    at checkArrays (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:87:17)
    at beginProcess (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:49:13)
    at module.exports (C:\Users\Xacheiree\Desktop\Projects\action-series-master\actions\universal-description-quicklinks.js:38:13)
    at nextTask (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:5310:14)```

**Comment by sethchilders92** [comment]
Did you run this on the Gauntlet or on a course?
