### ISSUE TITLE
Error in settings module item requirements

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#59]
Here is the error:
```
action-series-… error                     message: TypeError: Cannot set property 'type' of undefined stack: Error: TypeError: Cannot set property 'type' of undefined
    at module.exports (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\action-series-module-items\actions\module-items-requirements.js:66:22)
    at nextTask (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:958:16
    at modifyItemTitle (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\action-series-module-items\actions\module-items-naming-conventions.js:163:13)
    at module.exports (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\action-series-module-items\actions\module-items-naming-conventions.js:213:13)
    at nextTask (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\async\dist\async.js:958:16
    at module.exports (C:\Users\Xacheiree\Desktop\Projects\action-series-master\node_modules\action-series-module-items\actions\module-items-publish-settings.js:101:13)
```

Happened on the gauntlet.

**Comment by sethchilders92** [comment]
It works if the eachLimit in main.js is set to 1 instead of 20. Otherwise it doesn't work @zlw11063

**Comment by sethchilders92** [comment]
Changed to its own child module and ready for review @zlw11063 

https://github.com/byuitechops/module-item-requirements/
