### ISSUE TITLE
Fatal bug in universal target attributes

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#6]
```
if (!$(link).attr('href').includes('byui.instructure')) {
                                         ^

TypeError: Cannot read property 'includes' of undefined
    at links.forEach.link (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-target-attributes.js:17:42)
    at Array.forEach (<anonymous>)
    at action (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-target-attributes.js:14:19)
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-target-attributes.js:47:9)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at action (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-references.js:45:9)
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-references.js:53:9)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
```

**Comment by sethchilders92** [comment]
Ready for review. I made some changes to account for the error, but I am unsure as to which course you ran this on to get the error. I checked it on courseID: 10090 and Gauntlet 1 and got no errors. Let me know. @danverde
