### ISSUE TITLE
Fatal bug in action series universal rename

### ISSUE THREAD

**Issue by danverde** [byuitechops/action-series-master#8]
```
var itemsToRename = [{
                        ^

RangeError: Maximum call stack size exceeded
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-rename.js:10:25)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\action-series-master\actions\universal-styling-div.js:38:9)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2747:25
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
```

**Comment by danverde** [comment]
This was an issue with the action series in general, not this specific action. It was resolved by adding a setTimeout of 0, however switching the action series to promises would me a more stable solution.
